stages:
  - lint
  - test

image: python:3.10

before_script:
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pylint src/
  allow_failure: true  # optinal

test:
  stage: test
  script:
    - pytest --cov=src --cov-report=xml --cov-report=term-missing
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - coverage.xml
  coverage: '/TOTAL.*\s+(\d+%)/'
